# Generated by Django 3.1.2 on 2020-10-24 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutuslink',
            name='aboutUs',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='video',
        ),
        migrations.AddField(
            model_name='aboutuslink',
            name='about_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_us_links', to='api.aboutus'),
        ),
        migrations.AddField(
            model_name='aboutuslink',
            name='link_icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bloglink',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_links', to='api.blog'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebooks', to='api.category'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fieldweworkin',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='BlogVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=254, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_videos', to='api.blog')),
            ],
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='images')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_images', to='api.blog')),
            ],
        ),
    ]
