# Generated by Django 3.1.2 on 2020-10-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201024_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=20)),
                ('amount_discount', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='aboutuslink',
            name='link_icon_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
