# Generated by Django 3.1.2 on 2020-10-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201025_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
