# Generated by Django 3.1.2 on 2020-11-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201125_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='picture',
        ),
    ]
